# Generated by Django 5.0.7 on 2024-08-10 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_autodoc_user_delete_autodoct_delete_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoDoc',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 8, 59, 34, 822394, tzinfo=datetime.timezone.utc)),
        ),
    ]
