# Generated by Django 5.0.7 on 2024-08-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_user_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='published',
            field=models.DateTimeField(verbose_name='published at'),
        ),
    ]
