# Generated by Django 5.0.7 on 2024-08-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_user_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pssword',
            field=models.CharField(default='1111', max_length=100),
        ),
    ]
