# Generated by Django 5.0.7 on 2024-08-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_user_pssword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Usersinfo',
        ),
    ]
