# Generated by Django 5.0.7 on 2024-08-21 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_rename_pssword_usersinfo_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinfo',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at'),
        ),
    ]
